googleapis/gapic-generator-typescript

package.json, templates/typescript_gapic/package.json.njk
We need this to bring the new `compileProtos` script.
=> chore(deps): use google-gax v1.6.0

templates/typescript_gapic/package.json.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/test_application_ts/src/index.ts, typescript/test/testdata/echo_client_baseline.ts.txt
Since `google-gax` v1.7.2, `clientConfig` can be omitted. Marking it as not required everywhere.
=> fix: clientConfig can be omitted

templates/typescript_gapic/package.json.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, templates/typescript_gapic/tslint.json.njk, typescript/test/test_application_js/package.json, typescript/test/testdata/echo_client_baseline.ts.txt
We still have `@ts-ignore` in the places where we load protos dynamically, I need to think and figure out if we can get rid of them. But those are the only places.
=> fix: remove most of @ts-ignores from the generated code

templates/typescript_gapic/test/gapic-$service-$version.js.njk
Add paging method unit test for generated client library.
TODO: init request and response based on structure function, now the test only uses empty request to trigger the method and get empty response back.
#18
=> test: add paging method in unit test

typescript/src/generator.ts, typescript/src/schema/proto.ts, typescript/src/templater.ts
We use relative paths to templates which makes it hard to use the generator when the current working directory is different. Fixing that by passing the base path parameter to `nunjucks` in `nunjucks.configure`.
Not including any tests here because this is a refactor and existing tests cover this code (and they still work).
(also, ran `gts fix` that changed one unrelated function)
=> refactor: make sure templates can be located anywhere

templates/typescript_gapic/src/$version/$service_client.ts.njk
We had one `echo` left in the templates. Replacing it with the proper `{{ template }}`.
=> fix: fixing config name

templates/typescript_gapic/src/$version/$service_client.ts.njk
=> chore: operation should be exported only if an API has LRO

templates/typescript_gapic/_license.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, templates/typescript_gapic/src/$version/index.ts.njk, templates/typescript_gapic/src/index.ts.njk, templates/typescript_gapic/test/gapic-$service-$version.ts.njk
We do have a functionality in `templater.ts` to skip all files starting with `_`. Renaming `license.njk` to `_license.njk` and placing it to the root directory (where it makes sense for it to be).
=> fix: do not create empty license file

typescript/src/schema/naming.ts, typescript/test/unit/naming.ts
If we add `google/cloud/common_resources.proto` to the list of files to generate (i.e. append to `protoc` command), we get some problems:
1. It's from different package, so the naming logic breaks (it was originally supposed that all files from `protoc` command line are to be from the same package or have meaningful common package).
2. `google/longrunning/operation.proto` defines a service that we don't need to consider generating.
Cc: @lukesneeringer, @software-dov  since Python microgenerator might have similar logic.
=> fix: skip common or no-service protos when determining package name

docker/start.sh
We don't want it to be generated. It's a little bit hard to remove it from the generator code (some tests refactor is needed) so for now I'll just `rm -f` it from the Docker entry script.
=> fix: no proto.list

README.md
The wrong resource name is fixed in v0.6.1.
=> docs: use showcase v0.6.1

templates/typescript_gapic/_license.njk, templates/typescript_gapic/_util.njk, templates/typescript_gapic/package.json.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, templates/typescript_gapic/src/$version/$service_client_config.json.njk, templates/typescript_gapic/src/$version/$service_proto_list.json.njk, templates/typescript_gapic/src/$version/index.ts.njk, templates/typescript_gapic/src/index.ts.njk, templates/typescript_gapic/test/gapic-$service-$version.ts.njk, templates/typescript_gapic/tsconfig.json.njk, templates/typescript_gapic/tslint.json.njk, typescript/src/schema/api.ts, typescript/src/schema/comments.ts, typescript/src/schema/naming.ts, typescript/src/schema/proto.ts, typescript/src/templater.ts, typescript/src/util.ts, typescript/test/test_application_ts/src/index.ts, typescript/test/unit/api.ts, typescript/test/unit/codemap.ts, typescript/test/util.ts
Adding Apache 2.0 license to all our source files.
@bcoe Can we please have a license checker bot enabled on this repo? Thank you!
=> chore: add licenses to all files

package.json, typescript/tools/update-baselines.ts
Sometimes it's just boring to update them manually, so...
```sh
$ node build/tools/update-baselines.js
```
=> feat: a script to update baselines

.circleci/config.yml, templates/typescript_gapic/src/$version/$service_client.ts.njk, templates/typescript_gapic/tslint.json.njk, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/keymanager/tslint.json.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/showcase/tslint.json.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/texttospeech/tslint.json.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline, typescript/test/testdata/translate/tslint.json.baseline
1. `@ts-ignore` is bad  (`any` is also bad but better). Sooner or later we'll figure out how to get rid of that `any` as well.
2. To catch the problem that happened with `cloudbuild` (stopped compiling after `gts fix`), let's try compiling the generating code once more after fixing its formatting in CircleCI.
=> fix: no ts-ignore in generated code

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/src/schema/proto.ts
=> chore: move string manipulation methods to template

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/src/generator.ts, typescript/src/schema/proto.ts, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_proto_list.json.baseline
A set of fixes caused by manual comparison of the generated `translate` TS library with the original JS one.
1. Fully qualified types for long running operations (see the baseline changes for LRO types). It's what gapic-generator does, and it's very important for cases where we have several versions available (e.g. for `translate`, we'll have `v3beta1` and `v3` and we must load the correct versions of types).
2. Client headers: we should set `grpc` header if we use gRPC, set `gl-node` if we use Node.js, and set `gl-web` header if it's not Node.js (so it's likely a browser).
3. Removed handling of interface name in the code from `pagingResponseType()` since we now have it in the templates.
4. Do not include common protos (such as common resources) to the list of required proto files.
=> fix: compatibility with gapic-generator

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
More minor fixes:
- service comments moved on top of the file, before the `class` declaration
- fixed link to application default credentials
- removed `showcase` from output
- using the right `gax`
- minor formatting
=> fix: more minor fixes

package.json, templates/typescript_gapic/package.json.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, templates/typescript_gapic/test/gapic-$service-$version.ts.njk, typescript/test/test_application_js/index.js, typescript/test/test_application_ts/package.json, typescript/test/testdata/keymanager/package.json.baseline, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/keymanager/test/gapic-key_management_service-v1.ts.baseline, typescript/test/testdata/showcase/package.json.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/showcase/test/gapic-echo-v1beta1.ts.baseline, typescript/test/testdata/texttospeech/package.json.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/translate/package.json.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline, typescript/test/testdata/translate/test/gapic-translation_service-v3beta1.ts.baseline
1. add template for page streaming method
2. update unit test
3. update integration test
4. update baseline test
TODO: add comment for the new method, change `google-gax` version back for new release.
wait for: https://github.com/googleapis/gax-nodejs/pull/641
reference #112
=> feat: support pagestreaming method

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
Add function for page streaming comments and restructure util file
fix #112
=> feat: add comments for page stream method

templates/typescript_gapic/src/index.ts.njk, typescript/test/testdata/keymanager/src/index.ts.baseline, typescript/test/testdata/showcase/src/index.ts.baseline, typescript/test/testdata/texttospeech/src/index.ts.baseline, typescript/test/testdata/translate/src/index.ts.baseline
This improves our exports in `src/index.ts` and make the result of `require('library');` the same as it is now with JavaScript libraries.
(this still works with only one version!)
=> fix: better default exports in src/index.ts

templates/typescript_gapic/package.json.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/testdata/keymanager/package.json.baseline, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/showcase/package.json.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/texttospeech/package.json.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/translate/package.json.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
Using pagination types exported from `google-gax`.
CI won't work until gax v1.11.0 is released.
=> fix: use pagination types from gax

templates/typescript_gapic/system-test/fixtures/sample/src/index.js.njk, typescript/test/testdata/keymanager/system-test/fixtures/sample/src/index.js.baseline, typescript/test/testdata/showcase/system-test/fixtures/sample/src/index.js.baseline, typescript/test/testdata/texttospeech/system-test/fixtures/sample/src/index.js.baseline, typescript/test/testdata/translate/system-test/fixtures/sample/src/index.js.baseline
Making `eslint` happy about our generated system tests fixtures.
=> fix: add eslint disable instruction to system test fixture

templates/typescript_gapic/package.json.njk, templates/typescript_gapic/system-test/fixtures/sample/src/index.js.njk, templates/typescript_gapic/system-test/fixtures/sample/src/index.ts.njk, typescript/src/generator.ts, typescript/src/schema/api.ts, typescript/src/start_script.ts, typescript/test/testdata/texttospeech/package.json.baseline, typescript/test/testdata/texttospeech/system-test/fixtures/sample/src/index.js.baseline, typescript/test/testdata/texttospeech/system-test/fixtures/sample/src/index.ts.baseline, typescript/test/unit/extra-option.ts
fix #134 
User can pass package name using optional `--package-name` argument to generator.
=> feat: let user pass package name to the generator

.gitignore, docker/Dockerfile, docker/build.sh, docker/start.sh
This will save us some time on debugging. We'll remove it when we have proper versioning and auto-releases.
=> feat: show latest commit when running docker image

templates/typescript_gapic/test/gapic-$service-$version.ts.njk, typescript/test/testdata/keymanager/test/gapic-key_management_service-v1.ts.baseline, typescript/test/testdata/redis/test/gapic-cloud_redis-v1beta1.ts.baseline, typescript/test/testdata/showcase/test/gapic-echo-v1beta1.ts.baseline, typescript/test/testdata/texttospeech/test/gapic-text_to_speech-v1.ts.baseline, typescript/test/testdata/translate/test/gapic-translation_service-v3beta1.ts.baseline
Minor fixes for the generated unit tests:
- include version in `describe()` title so that if the library has multiple versions, it's immediately clear which version's tests fail;
- do not emit `mockSimpleGrpcMethod` if there are no simple methods (will fix the long standing https://github.com/googleapis/gapic-generator/issues/2120 that only affects video-intelligence API)
- proper name for fallback test.
=> fix: generated test fixes

typescript/src/schema/proto.ts, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/redis/test/gapic-cloud_redis-v1beta1.ts.baseline
When trying to convert redis in https://github.com/googleapis/nodejs-redis/pull/236 we found that our logic for determining if the method should be auto-paginated or not must be improved (according to the last paragraph of [AIP 4233](https://aip.dev/client-libraries/4233)).
> **Note:** If the response message has more than one non-primitive `repeated` field, the first one (in order of appearance in the file _and_ field number) is used. If the first field by order of appearance in the message and the first field by field number do not match, code generators that implement automatic pagination **should** fail with an error.
=> fix: correctly determine auto-paginated field

templates/typescript_gapic/webpack.config.js.njk, typescript/test/testdata/keymanager/webpack.config.js.baseline, typescript/test/testdata/redis/webpack.config.js.baseline, typescript/test/testdata/showcase/webpack.config.js.baseline, typescript/test/testdata/texttospeech/webpack.config.js.baseline, typescript/test/testdata/translate/webpack.config.js.baseline
Minor fix: some packages depend on `http-proxy-agent` (not just `https-proxy-agent`) which we don't need in webpack bundle. Replacing it with `null-loader` as well.
=> fix: ignore http-proxy-agent for webpack

templates/typescript_gapic/package.json.njk, typescript/test/testdata/keymanager/package.json.baseline, typescript/test/testdata/redis/package.json.baseline, typescript/test/testdata/showcase/package.json.baseline, typescript/test/testdata/texttospeech/package.json.baseline, typescript/test/testdata/translate/package.json.baseline
Fixes #130.
This only affects the new libraries.
=> fix: use c8 for coverage

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/src/schema/proto.ts, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
A set of template changes to properly convert the return types of the calls to TypeScript types. It's hard to get an idea from reading the diff; the three main changes are these:
1. Be more careful when converting types for auto-pagination. Sometimes the pagination result is a basic type like `string` (it affects Firestore). So, when dumping types, if it's a basic TypeScript type, dump it as is:
2. Same problem: pagination type is not always a message, might be a primitive type as well.
3. Proper type conversion (the old code incorrectly produced `number` instead of `number[]` in JSDoc comments).
Upd. Minor fixes to remove extra spaces that make the result so hard to read :(
=> fix: mapping proto types to TypeScript types

templates/typescript_gapic/package.json.njk, typescript/test/testdata/keymanager/package.json.baseline, typescript/test/testdata/redis/package.json.baseline, typescript/test/testdata/showcase/package.json.baseline, typescript/test/testdata/texttospeech/package.json.baseline, typescript/test/testdata/translate/package.json.baseline
As discussed in #161 - let's generate the code with TypeScript 3.6, because 3.7 breaks things.
=> fix: use TypeScript 3.6 in the generated code

templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
Fixes https://github.com/googleapis/gapic-generator/issues/2127 by exposing service stub directly. All the extra logic that needs to have a service stub can then depend on this new field.
@callmehiphop: this will help us remove changes to the generated code in Pub/Sub.
=> feat: expose service stub as public member

docker/Dockerfile, docker/start.sh
Minor fix: we want this debug file with `git log` output be readable for every `--user`. Not related to the current problems caused by `--user` flag but uncovered while debugging.
=> fix: make git log file readable by everyone

typescript/src/schema/api.ts, typescript/src/schema/proto.ts, typescript/test/protos/google/cloud/common_resources.proto
Fixes #168. A little bit of refactor around resources brings support for file-level options with resource definitions, such as
```
option (google.api.resource_definition) = {
type: "locations.googleapis.com/Location"
pattern: "projects/{project}/locations/{location}"
};
```
Baselines do not change since I update the `common_resources.proto` to the new format in the same PR.
=> feat: support file-level resource annotations

templates/typescript_gapic/_util.njk, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
Fixes https://github.com/googleapis/gax-nodejs/issues/637 by updating documentation to explain when to expect `rawResponse`.
Improves the jsdoc documentation for pagination and server streaming.
=> fix: correct jsdoc for server streaming and pagination

typescript/src/schema/proto.ts, typescript/test/testdata/keymanager/src/v1/key_management_service_client_config.json.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client_config.json.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client_config.json.baseline, typescript/test/testdata/texttospeech/src/v1/text_to_speech_client_config.json.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client_config.json.baseline, typescript/test/unit/codemap.ts
Cc: @schmidt-sebastian 
These timeout values will soon be removed from gax because they are not supported in new gRPC service config, but for now, since gax still uses them, let's set them to 60s and not 20s.
=> fix: set default timeouts to 60000

templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/src/schema/proto.ts
After some thinking I realized that #173 is better to be fixed in templates.
@schmidt-sebastian The idea here is to leave all TypeScript specifics in templates, and the general logic in the code. If we ever decide to generate some other language with the same code, it should only need the new templates and hopefully no code changes (not that we really planned that, but it's a good guidance). So I just moved `.toCamelCase()` from one place to another :)
=> fix: proper handling of paging field name

typescript/src/schema/api.ts, typescript/src/schema/proto.ts, typescript/src/schema/resourceDatabase.ts, typescript/test/unit/resourceDatabase.ts
This PR adds support for `.child_type`, also moving most of the resource related code into a separate `ResourceDatabase` class.
After talking to @noahdietz and @lukesneeringer, it turns out that the easiest way to support `.child_type` is to split the corresponding pattern by segments, then find all possible prefixes that correspond to known resources, and register them (to generate helper functions later).
No baseline changes (that means that the APIs included in baselines are not affected). The first known affected API is datacatalog (cc: @bcoe - this should fix it).
Note: we only support the first pattern of multi-pattern resources for now, hence `[0]` here and there. This will be taken care of separately in January, since it will be an incompatible change.
=> feat: parse child_type resource

templates/typescript_gapic/_util.njk, typescript/test/test_application/test_ts.ts
=> fix: escape /*/ in method comments

templates/typescript_gapic/src/$version/$service_client.ts.njk
Path template names must be camel-cased, not lowercased. This issue created compatibility problem in https://github.com/googleapis/nodejs-datacatalog/issues/79.
=> fix: use camel case for path template names

README.md, templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/protos/google/showcase/v1beta1/echo.proto, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/showcase/protos/google/showcase/v1beta1/echo.proto.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
For all trailing whitespace haters (looking at you @JustinBeckwith and @schmidt-sebastian :) ), here we go :) A little bit of `find templates typescript README.md -type f | xargs perl -pi -e 's/[\s\r]+\n/\n/g'` plus a small change in the templates to make sure the generated comments also have no trailing whitespace. Enjoy!
=> fix: trim trailing whitespace in code, templates, and generated code

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/index.d.ts, typescript/src/util.ts, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/unit/util.ts
In https://github.com/googleapis/nodejs-bigquery-storage/pull/1 we see that the last element of `request.tableReference.project_id` should also be in the camel case (`request.tableReference.projectId`), otherwise it won't match the TypeScript type.
Fixing this in both client and unit test templates.
Also, the headers should still contain `table_reference.project_id` (snake case, joined with a dot), not just one snake cased line as now.
=> fix: camelCase more proto identifiers

typescript/src/schema/resourceDatabase.ts, typescript/test/unit/resourceDatabase.ts
Fixes #204. We should allow underscores and possible trailing `=**`, but not digits.
=> fix: resource ids can contain underscores and trailing characters

docker/Dockerfile
Alpine got broken :)  They removed `__strftime_l` from `/lib64/ld-linux-x86-64.so.2` (it existed in `libc6-compat-1.1.20-r5` but is missing in `libc6-compat-1.1.24-r0`, I'm guessing it's [this commit](https://gitlab.alpinelinux.org/alpine/aports/commit/f6baa2aad98a418cd21b857f825e772a987b7c93#0b6ead39bf26fd40f7e2f862e39d543f2821fca3_0_19) that causes it.
`protoc` binary needs this symbol:
```
/lib64/ld-linux-x86-64.so.2 (0x7f7a983cf000)
libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7a983cf000)
libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f7a983cf000)
libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f7a983cf000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bin/protoc)
Error relocating /usr/local/bin/protoc: __strftime_l: symbol not …
```
=> fix: use ubuntu-based image instead of alpine-based, update protoc

templates/typescript_gapic/src/$version/$service_client.ts.njk
```
incidentRoleAssignmentPath(
project_id_or_number: string,
incident_id: string,
role_id: string
) {
return this._pathTemplates.incidentroleassignmentPathTemplate.render({
project_id_or_number,
incident_id,
role_id,
});
}
```
tslint fail for `variable name must be in lowerCamelCase or UPPER_CASE`
=> fix: parameters should be camelcase in path template function

typescript/src/schema/api.ts, typescript/src/schema/naming.ts, typescript/test/unit/naming.ts
fix #214 
If no common prefix package name is found, but users specify `main-service` option, we will take the package with the `main-service` name as root package. If `main-service` is not set, error will be thrown.
=> feat: support proto packages in different namespace

typescript/src/schema/api.ts, typescript/test/testdata/dlp/src/v2/dlp_service_proto_list.json.baseline, typescript/test/unit/api.ts
We got some PRs that changed only the order of protos after proto update (maybe because the file update time was somehow used in the default ordering). I think it's a good time to make the order fixed.
Example PRs: https://github.com/googleapis/nodejs-monitoring/pull/353, https://github.com/googleapis/nodejs-datacatalog/pull/101, https://github.com/googleapis/nodejs-datalabeling/pull/119
@bcoe This will likely cause some autosynth PRs with reordering, I will take care of those, and then it should reduce the amount of proto-rearranging PRs.
=> fix: make sure the order of protos is fixed

typescript/src/schema/api.ts, typescript/src/schema/proto.ts, typescript/src/schema/resourceDatabase.ts, typescript/test/testdata/dlp/src/v2/dlp_service_client.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
We generated all resources into pathTemplates only if:
1. Message or fields with `google.api.resource` option
2. Options that have `google.api.resource_definition` and are referenced by some messages or fields.
Also, sort pathTemplate to avoid random test failure.
For dlp baseline test, `organization` is not referenced in proto, so get removed by logic.
This should unblock `securitycenter` API conversion to typescript: https://github.com/googleapis/nodejs-security-center/pull/198#event-2998450223
=> feat!: generate all api resources and resource definition which is referenced.

templates/typescript_gapic/_util.njk, templates/typescript_gapic/src/$version/$service_client.ts.njk, templates/typescript_gapic/test/gapic-$service-$version.ts.njk, typescript/src/schema/proto.ts, typescript/test/testdata/dlp/test/gapic-dlp_service-v2.ts.baseline, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/keymanager/test/gapic-key_management_service-v1.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/redis/test/gapic-cloud_redis-v1beta1.ts.baseline, typescript/test/testdata/showcase/test/gapic-echo-v1beta1.ts.baseline, typescript/test/testdata/translate/test/gapic-translation_service-v3beta1.ts.baseline, typescript/test/unit/proto.ts
BigQuery Storage API has this fun annotation:
```proto
rpc CreateReadSession(CreateReadSessionRequest) returns (ReadSession) {
option (google.api.http) = {
post: "/v1beta1/{table_reference.project_id=projects/*}"
body: "*"
additional_bindings {
post: "/v1beta1/{table_reference.dataset_id=projects/*/datasets/*}"
body: "*"
}
};
...
}
```
Both `table_reference.project_id` and `table_reference.dataset_id` must go into `x-goog-request-params` header, otherwise the server returns an error.
Fixing this problem. Also, the fix exposed a small problem in the page streaming test, fixing it as well.
@steffnay This, when released, will finally unblock you!
=> feat: support additional_bindings in google.api.http option

templates/typescript_gapic/linkinator.config.json.njk, typescript/test/testdata/dlp/linkinator.config.json.baseline, typescript/test/testdata/keymanager/linkinator.config.json.baseline, typescript/test/testdata/redis/linkinator.config.json.baseline, typescript/test/testdata/showcase/linkinator.config.json.baseline, typescript/test/testdata/texttospeech/linkinator.config.json.baseline, typescript/test/testdata/translate/linkinator.config.json.baseline
I had to close out a bunch of the autosynth PRs because we had landed this everywhere without updating the generator :)
=> fix: ignore img.shields.io in linkinator

typescript/src/cli.ts, typescript/src/schema/api.ts, typescript/test/unit/api.ts
We should throw error if generated client library is empty.
Need feedback of error message @alexander-fenster @xiaozhenliu-gg5 🙏
=> fix: throw err when fail to get service name list

typescript/src/schema/proto.ts, typescript/src/schema/resourceDatabase.ts, typescript/test/testdata/dlp/src/v2/dlp_service_client.ts.baseline, typescript/test/testdata/monitoring/src/v3/service_monitoring_service_client.ts.baseline, typescript/test/testdata/monitoring/src/v3/uptime_check_service_client.ts.baseline
As @JustinBeckwith pointed out [here](https://github.com/googleapis/nodejs-tasks/pull/350#discussion_r375907862), the path templates are not really sorted (well, they are, but nobody knows how exactly).
Fixing that, and also removing path templates with no parameters (such as `*`) from the database, since we cannot possibly generate any useful helper function for them.
=> fix: sort path templates, ignore useless templates

typescript/src/generator.ts, typescript/src/schema/api.ts, typescript/src/schema/naming.ts, typescript/test/unit/api.ts
One more attempt to fix the common services problem properly. This time, let's move all the similar checks into one place (a public static method of the `API` class).
=> fix: include IAM into common services to ignore, refactor the code

templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/testdata/dlp/src/v2/dlp_service_client.ts.baseline, typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline, typescript/test/testdata/monitoring/src/v3/service_monitoring_service_client.ts.baseline, typescript/test/testdata/monitoring/src/v3/uptime_check_service_client.ts.baseline, typescript/test/testdata/redis/src/v1beta1/cloud_redis_client.ts.baseline, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline, typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
Turns out BigQuery Storage API actually cares about the `x-goog-request-params` being passed for all methods, including streaming.
Cc: @steffnay
=> fix: pass x-goog-request-params to streaming methods

templates/typescript_gapic/src/$version/$service_client.ts.njk, typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
This fixes the problem @hkdevandla just found with the Showcase Messaging API. The problem is not shown by our existing tests but in Messaging API we had a client streaming method that had a request parameter (which did not make any sense because client streaming methods have no request object).
@xiaozhenliu-gg5 Maybe we can add Messaging API to the Showcase tests as well?  If we add those protos to our Showcase folder it will give us better coverage almost for free.
Introduced today by me in #234 :)
=> fix: client streaming do not have request

typescript/src/start_script.ts, typescript/test/testdata/monitoring/protos/google/monitoring/v3/service_service.proto.baseline, typescript/test/testdata/monitoring/protos/google/monitoring/v3/uptime_service.proto.baseline
Problem: fail to copy proto files from proto.list because the duplicate in common google-gax and input proto files.
The original logic is to copy the proto files which are **not** in google-gax.
Fixed logic is to copy the proto file **either** from input proto files from cmd **or** not in google-gax, which also means that skip the proto file in gax common protos **and** not in cmd input proto files
I didn't add extra unit test for this case, because monitoring library cover this case as well. Let me know if you have concern.
----------------------------|---------|----------|---------|---------|------------------------------
File                        | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s            
----------------------------|---------|----------|---------|------- …
=> fix: copy protos in common google gax and googleapis

renovate.json
We don't mind running renovate 24x7 here. The schedule was important for client libraries so renovate won't spam the CI during the work day, but it's OK for this one repo to remove the schedule.
=> chore: remove renovate schedule

package.json
Fixing docker image that I broke with #240 :)
Just before packing, remove the symlink (not supported by `npm`). Right after packing, put it back.
=> fix: fix docker image with symlinks

renovate.json
1. `"upgradeInRange": true` will ask Renovate to send PRs for updates that are covered by a range. I.e. `google-gax` dependency is currently set to `^1.12.0` and since the latest version `1.14.1` is within that range, we don't get a PR. We want the generated libraries to have the very latest dependencies listed, so we actually want to see PRs for these updates.
2. Set assignees for Renovate PRs.
=> chore: more fixes to renovate.json

typescript/tools/update-baselines.ts
We just want `npm run baseline` to create the `package.json.baseline` symlinks properly.
Background: #240 - to make renovate bot update our baselines, we renamed `package.json.baseline` to `package.json` there in baselines folder, and created a symlink to have the baseline test logic work.
=> fix: make npm run baseline behave properly with symlinks

baselines/dlp/.jsdoc.js.baseline, baselines/kms/.jsdoc.js.baseline, baselines/monitoring/.jsdoc.js.baseline, baselines/redis/.jsdoc.js.baseline, baselines/showcase/.jsdoc.js.baseline, baselines/texttospeech/.jsdoc.js.baseline, baselines/translate/.jsdoc.js.baseline, templates/typescript_gapic/.jsdoc.js.njk
@summer-ji-eng will send one more mass PR (for a different reason - to add `protos` folder everywhere), so it's also a good time to fix formatting here :)
=> fix: no double quotes in .jsdoc.js

typescript/tools/update-baselines.ts
Finally, making `npm run baseline` work properly again.
=> fix: make sure npm run baseline creates proper symlinks

baselines/bigquery-storage/src/v1beta1/big_query_storage_client.ts.baseline, baselines/dlp/src/v2/dlp_service_client.ts.baseline, baselines/kms/src/v1/key_management_service_client.ts.baseline, baselines/monitoring/src/v3/alert_policy_service_client.ts.baseline, baselines/monitoring/src/v3/group_service_client.ts.baseline, baselines/monitoring/src/v3/metric_service_client.ts.baseline, baselines/monitoring/src/v3/notification_channel_service_client.ts.baseline, baselines/monitoring/src/v3/service_monitoring_service_client.ts.baseline, baselines/monitoring/src/v3/uptime_check_service_client.ts.baseline, baselines/redis/src/v1beta1/cloud_redis_client.ts.baseline, baselines/showcase/src/v1beta1/echo_client.ts.baseline, baselines/showcase/src/v1beta1/identity_client.ts.baseline, baselines/showcase/src/v1beta1/messaging_client.ts.baseline, baselines/showcase/src/v1beta1/testing_client.ts.baseline, baselines/texttospeech/src/v1/text_to_speech_client.ts.baseline, baselines/translate/src/v3beta1/translation_service_client.ts.baseline, templates/typescript_gapic/src/$version/$service_client.ts.njk
As discussed in the chat: let's not accept promise as a client constructor parameter. The correspondng google-gax PR is coming.
Cc: @xiaozhenliu-gg5 @summer-ji-eng
=> feat: do not mention overriding Promise

typescript/src/generator.ts, typescript/src/schema/proto.ts, typescript/src/start-script.ts, typescript/src/templater.ts, typescript/test/unit/baselines.ts, typescript/test/util.ts
This is extracted from #322 to make that PR only related to samples generation.
Here I'm allowing to pass `--template` parameter pointing to a semicolon-separated list of template folders to process (by default, it's `typescript_gapic`). It will be helpful in making the generator more flexible.
=> refactor: allow passing multiple templates as parameters

baselines/logging/src/v2/logging_service_v2_client.ts.baseline, templates/typescript_gapic/src/$version/$service_client.ts.njk
pubsub has subresponse_field set in batching params and it's rendering as 
```
this._descriptors.batching = {
publish: new gaxModule.BundleDescriptor(
'messages',
['topic'],
messageIds,
gax.createByteLengthFunction(
protoFilesRoot.lookup('google.pubsub.v1.PubsubMessage')
)
),
};
```
correct one should be:
```
this._descriptors.batching = {
publish: new gaxModule.BundleDescriptor(
'messages',
['topic'],
'messageIds',
gax.createByteLengthFunction(
protoFilesRoot.lookup('google.pubsub.v1.PubsubMessage')
)
),
};
```
=> fix: render subresponse_field as string if it is not null

baselines/bigquery-storage/src/v1beta1/big_query_storage_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/echo_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/identity_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/messaging_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/testing_client.ts.baseline, baselines/dlp/src/v2/dlp_service_client.ts.baseline, baselines/kms/src/v1/key_management_service_client.ts.baseline, baselines/logging/src/v2/config_service_v2_client.ts.baseline, baselines/logging/src/v2/logging_service_v2_client.ts.baseline, baselines/logging/src/v2/metrics_service_v2_client.ts.baseline, baselines/monitoring/src/v3/alert_policy_service_client.ts.baseline, baselines/monitoring/src/v3/group_service_client.ts.baseline, baselines/monitoring/src/v3/metric_service_client.ts.baseline, baselines/monitoring/src/v3/notification_channel_service_client.ts.baseline, baselines/monitoring/src/v3/service_monitoring_service_client.ts.baseline, baselines/monitoring/src/v3/uptime_check_service_client.ts.baseline, baselines/redis/src/v1beta1/cloud_redis_client.ts.baseline, baselines/showcase/src/v1beta1/echo_client.ts.baseline, baselines/showcase/src/v1beta1/identity_client.ts.baseline, baselines/showcase/src/v1beta1/messaging_client.ts.baseline, baselines/showcase/src/v1beta1/testing_client.ts.baseline, baselines/texttospeech/src/v1/text_to_speech_client.ts.baseline, baselines/translate/src/v3beta1/translation_service_client.ts.baseline, templates/typescript_gapic/src/$version/$service_client.ts.njk
ref: https://github.com/googleapis/gapic-generator-typescript/pull/343 part of the gts v2 change.
=> fix: gts linter complains about prefer-spread

baselines/bigquery-storage/package.json, baselines/disable-packing-test/package.json, baselines/dlp/package.json, baselines/kms/package.json, baselines/logging/package.json, baselines/monitoring/package.json, baselines/redis/package.json, baselines/showcase/package.json, baselines/texttospeech/package.json, baselines/translate/package.json, package.json, templates/typescript_gapic/package.json
1. sort package-json
2. sort package-json in templates
This will avoid some diff noise during API conversion.
=> feat: sort package-json for generator to avoid noise in API conversion

baselines/logging/test/gapic_logging_service_v2_v2.ts.baseline, templates/typescript_gapic/_util.njk, templates/typescript_gapic/test/gapic_$service_$version.ts.njk, typescript/src/schema/proto.ts
fix: #380 
Now if the pagingResponseType is not `TYPE_MESSAGE`, we will use `.google.google.protobuf.FieldDescriptorProto.Type.TYPE_STRING (type field)` as the return type.
1.  In _util it will be truncated as `string` in primitive type check for client template. 
2. use `String` to create object for `generateSampleMessage` for unit test.
Only `logging` baseline got changed and start to use the new object.
=> fix: unit test template has wrong paging response type

docker/test.sh, src/gapic-generator-typescript.ts
This is for `dialogflow` special, by default we should run validator for all proto files.
=> fix: add option to disable validator 

src/gapic-generator-typescript.ts
TWIL: `const validation = argv.validation as string | 'true';` is not setting the default value to be true.
`const validation = argv.validation ?? 'true';` does the job.
=> fix: fix the default value of validation option

baselines/asset/tsconfig.json.baseline, baselines/bigquery-storage/tsconfig.json.baseline, baselines/disable-packing-test/tsconfig.json.baseline, baselines/dlp/tsconfig.json.baseline, baselines/kms/tsconfig.json.baseline, baselines/logging/tsconfig.json.baseline, baselines/monitoring/tsconfig.json.baseline, baselines/redis/tsconfig.json.baseline, baselines/showcase/tsconfig.json.baseline, baselines/tasks/tsconfig.json.baseline, baselines/texttospeech/tsconfig.json.baseline, baselines/translate/tsconfig.json.baseline, baselines/videointelligence/tsconfig.json.baseline, templates/typescript_gapic/tsconfig.json.njk
Fixes #479 - we can now use `es2018` as a target for new libraries (all existing should already be at `es2018` after the Node 8 deprecation party).
=> fix: use es2018 as a target

.circleci/config.yml
Updates the version of the gapic-config-validator assets downloaded by CI. There were no changes to the `gapic-error-conformance` tool in this release.
=> chore: update gapic-config-validator version in ci

WORKSPACE, repositories.bzl
Putting all `http_archive` rules to a separate file to avoid copying URLs and versions of dependencies to the googleapis `WORKSPACE` file.
=> feat: list external dependencies in repositories.bzl

docker/Dockerfile, docker/build.sh, docker/publish.sh, docker/test.sh
Fixes https://github.com/googleapis/synthtool/issues/605 - apparently, in the latest `protoc` (3.12.3) they lost an executable bit for "others" in their released zip archive. Added an extra `chmod` in our `Dockerfile` to make our Docker image work with `--user`.
=> fix: chmod protoc in docker image

baselines/asset/package.json, baselines/bigquery-storage/package.json, baselines/disable-packing-test/package.json, baselines/dlp/package.json, baselines/kms/package.json, baselines/logging/package.json, baselines/monitoring/package.json, baselines/redis/package.json, baselines/showcase/package.json, baselines/tasks/package.json, baselines/texttospeech/package.json, baselines/translate/package.json, baselines/videointelligence/package.json, package.json, templates/typescript_gapic/package.json, yarn.lock
For some unknown reason, we use `@types/node` v12 for the generated libraries, and v13 for the generator itself. There is no reason not to use v14 for everything and save on the number of Renovate PRs.
=> chore(deps): use @types/node v14

test-fixtures/test-application-ts/package.json
When I bumped all `@types/node` versions yesterday in #556 I apparently missed this one.
=> chore(deps): use @types/node v14 in test app

baselines/asset/src/v1/asset_service_client.ts.baseline, baselines/bigquery-storage/src/v1beta1/big_query_storage_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/echo_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/identity_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/messaging_client.ts.baseline, baselines/disable-packing-test/src/v1beta1/testing_client.ts.baseline, baselines/dlp/src/v2/dlp_service_client.ts.baseline, baselines/kms/src/v1/key_management_service_client.ts.baseline, baselines/logging/src/v2/config_service_v2_client.ts.baseline, baselines/logging/src/v2/logging_service_v2_client.ts.baseline, baselines/logging/src/v2/metrics_service_v2_client.ts.baseline, baselines/monitoring/src/v3/alert_policy_service_client.ts.baseline, baselines/monitoring/src/v3/group_service_client.ts.baseline, baselines/monitoring/src/v3/metric_service_client.ts.baseline, baselines/monitoring/src/v3/notification_channel_service_client.ts.baseline, baselines/monitoring/src/v3/service_monitoring_service_client.ts.baseline, baselines/monitoring/src/v3/uptime_check_service_client.ts.baseline, baselines/redis/src/v1beta1/cloud_redis_client.ts.baseline, baselines/showcase/src/v1beta1/echo_client.ts.baseline, baselines/showcase/src/v1beta1/identity_client.ts.baseline, baselines/showcase/src/v1beta1/messaging_client.ts.baseline, baselines/showcase/src/v1beta1/testing_client.ts.baseline, baselines/tasks/src/v2/cloud_tasks_client.ts.baseline, baselines/texttospeech/src/v1/text_to_speech_client.ts.baseline, baselines/translate/src/v3beta1/translation_service_client.ts.baseline, baselines/videointelligence/src/v1/video_intelligence_service_client.ts.baseline, templates/typescript_gapic/src/$version/$service_client.ts.njk
This will properly fix the problem reported in https://github.com/googleapis/nodejs-speech/issues/547 and https://github.com/googleapis/nodejs-vision/issues/573. The existing code did not work for Electron (which has `window` defined but does not follow `browser` field in `package.json` so it picked the wrong non-fallback `google-gax` implementation).
The new code is just simpler. It should work properly for webpack+browsers (since `webpack` respects `browser` field in `google-gax` and will get the fallback implementation), and for Electron, users will need to pass `{fallback: true}` to the client constructor.
=> fix: make fallback work properly in Electron

rules_typescript_gapic/typescript_gapic.bzl, src/generator.ts
Handling extra plugin parameters properly.
Also, adding a debug print to simplify transitioning from Docker containers to Bazel builds.
=> fix: make plugin parameters work properly
