- typescript/test/test_application_ts/src/index.ts
Small improvements to TypeScript test application:
- `gts fix`
- using extra return values from LRO operation
> test: gts fix and LRO extra parameters support in TS app

- .gitignore
- templates/typescript_gapic/src/$version/$service_client_config.json.njk
#54 update service config json template
> chore: service config generated properly

- templates/typescript_gapic/src/$version/$service_client.ts.njk
- typescript/src/schema/api.ts
- typescript/src/schema/comments.ts
- typescript/src/schema/proto.ts
- typescript/test/testdata/keymanager/src/v1/keymanagementservice_client.ts.baseline
- typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
> chore: add comments on service & method level

- package.json
> fix: add templates to the package

- templates/typescript_gapic/package.json.njk
- templates/typescript_gapic/src/$version/$service_client.ts.njk
- typescript/test/testdata/keymanager/package.json.baseline
- typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline
- typescript/test/testdata/showcase/package.json.baseline
- typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
- typescript/test/testdata/texttospeech/package.json.baseline
- typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline
Preventing issues like https://github.com/googleapis/nodejs-translate/pull/361.
> fix: make sure npm pack works

- .circleci/config.yml
- templates/typescript_gapic/package.json.njk
- templates/typescript_gapic/test/gapic-$service-$version.ts.njk
- typescript/test/testdata/keymanager/package.json.baseline
- typescript/test/testdata/keymanager/test/gapic-key_management_service-v1.ts.baseline
- typescript/test/testdata/showcase/package.json.baseline
- typescript/test/testdata/showcase/test/gapic-echo-v1beta1.ts.baseline
- typescript/test/testdata/texttospeech/package.json.baseline
- typescript/test/testdata/texttospeech/test/gapic-text_to_speech-v1.ts.baseline
- typescript/test/testdata/translate/package.json.baseline
- typescript/test/testdata/translate/test/gapic-translation_service-v3beta1.ts.baseline
Replace `require` with `import`, fix some types.
> fix: make generated test more TypeScript-y

- templates/typescript_gapic/package.json.njk
- typescript/test/testdata/keymanager/package.json.baseline
- typescript/test/testdata/showcase/package.json.baseline
- typescript/test/testdata/texttospeech/package.json.baseline
- typescript/test/testdata/translate/package.json.baseline
Need to use newer `gts` and `typescript` in the generated code.
> fix(deps): use gts ^1.0.0 and typescript ~3.6.0

- README.md
Adding some very basic `README.md`.
> docs: a little bit of README

- templates/typescript_gapic/_util.njk
- templates/typescript_gapic/src/$version/$service_client.ts.njk
- typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline
- typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
- typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline
- typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
> chore: add options to comments for all methods

- templates/typescript_gapic/_util.njk
- templates/typescript_gapic/src/$version/$service_client.ts.njk
- typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
1. remove request comment for client/bidi streaming method
2. update return comment for client/bidi streaming method
3. update baseline
> chore: remove request comment for bidi/client streaming method

- templates/typescript_gapic/_util.njk
- templates/typescript_gapic/src/$version/$service_client.ts.njk
- typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline
- typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
- typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline
- typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
Checked the compiled js client file does have all proper comments now.
> chore: move js doc around

- package.json
> chore: an npm script to update baseline

- package.json
- templates/typescript_gapic/_util.njk
- templates/typescript_gapic/src/$version/$service_client.ts.njk
- typescript/src/schema/api.ts
- typescript/src/schema/comments.ts
- typescript/src/schema/proto.ts
- typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline
- typescript/test/testdata/showcase/src/v1beta1/echo_client.ts.baseline
- typescript/test/testdata/texttospeech/src/v1/text_to_speech_client.ts.baseline
- typescript/test/testdata/translate/src/v3beta1/translation_service_client.ts.baseline
1. optional parameter should be in square brackets
2. all parameters are in camel case.
> chore: optional parameter should be in square brackets and camel case

- typescript/src/generator.ts
- typescript/src/schema/api.ts
- typescript/src/schema/comments.ts
- typescript/src/schema/proto.ts
I just searched for `&&` in the code and replaced a lot of occurrences with optional chaining operator (and `??` operator in one case). That's really cool! :)  (@bcoe FYI)
> refactor: use optional chaining

- README.md
Otherwise, it will create files as root on Linux.
Also, better formatting of README :)
> docs: README: use --user in docker run

- templates/typescript_gapic/.gitignore.njk
- typescript/test/testdata/dlp/.gitignore.baseline
- typescript/test/testdata/keymanager/.gitignore.baseline
- typescript/test/testdata/redis/.gitignore.baseline
- typescript/test/testdata/showcase/.gitignore.baseline
- typescript/test/testdata/texttospeech/.gitignore.baseline
- typescript/test/testdata/translate/.gitignore.baseline
Fixes #193.
* add .gitignore template
* testdata generated .gitignore file
> feat: populate a minimal .gitignore

- typescript/src/schema/comments.ts
- typescript/src/schema/proto.ts
Seems like I forgot to remove some logging :) Also, removed the `// console.warn()` that was there for ages.
> fix: remove extra logging

- docker/test.sh
It broke after moving protos around in #241.
> fix: fix docker test

- baselines/dlp/package.json
- baselines/kms/package.json
- baselines/monitoring/package.json
- baselines/redis/package.json
- baselines/showcase/package.json
- baselines/texttospeech/package.json
- baselines/translate/package.json
- package.json
- templates/typescript_gapic/package.json
Let's not be too aggressive with TypeScript versions.
> fix(deps): use typescript ~3.7.5 for now

- baselines/dlp/.jsdoc.js.baseline
- baselines/kms/.jsdoc.js.baseline
- baselines/monitoring/.jsdoc.js.baseline
- baselines/package.json.njk
- baselines/redis/.jsdoc.js.baseline
- baselines/showcase/.jsdoc.js.baseline
- baselines/texttospeech/.jsdoc.js.baseline
- baselines/translate/.jsdoc.js.baseline
- templates/typescript_gapic/.jsdoc.js.njk
- correct system name using library package name
- remove source html files
> fix: template for configuring jsdoc

- baselines/bigquery-storage/linkinator.config.json.baseline
- baselines/dlp/linkinator.config.json.baseline
- baselines/kms/linkinator.config.json.baseline
- baselines/monitoring/linkinator.config.json.baseline
- baselines/redis/linkinator.config.json.baseline
- baselines/showcase/linkinator.config.json.baseline
- baselines/texttospeech/linkinator.config.json.baseline
- baselines/translate/linkinator.config.json.baseline
- templates/typescript_gapic/linkinator.config.json.njk
Concurrency 10 seems to work better on GitHub Actions.
> fix: set linkinator to silent, concurrency 10

- renovate.json
Thanks @noahdietz for this hint :)
> chore(renovate): reviewers, not assignees

- baselines/disable-packing-test/protos/google/showcase/v1beta1/identity.proto.baseline
- templates/typescript_gapic/package.json
Remove invalid lines in package.json for renovate automatically updating the dependencies.
> fix: fix package.json for renovate
